# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
production:
  gmail_username: "heather.allaman@gmail.com"
  gmail_password: "DollyBaby1984"
  aws_bucket: "willowbride"
  aws_key_id: "AKIAITDF5CWTU4XDBR4A"
  aws_access_key: "6KSZ1Rb4Dc9d+OVHeEZrL6PG/m1qRh2H3G5J22Nf"

